<!doctype html><html lang=ja><head><meta http-equiv=x-clacks-overhead content="GNU Terry Pratchett"><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>GKE 上にて Pythonで logger.info() を行うとCloud logging では stderr に保存され、すべてエラーになる問題への対処法 | hurutoriya</title><meta name=title content="GKE 上にて Pythonで logger.info() を行うとCloud logging では stderr に保存され、すべてエラーになる問題への対処法"><meta name=description content="Python のアプリケーションで、Cloud logger にログを出力したいときに
標準の Python logging モジュールを利用して、ログを出力する Python Cloud Logging package を使用する 上記の２つの方法があります。
不必要にパッケージを増やしたくはないので、1 の標準モジュールで Cloud Logger へ出力できないか試してみました。
標準の Python logging モジュールを試す 標準の logging モジュールでログを出力したいときに
import logging logger = logging.getLogger(__name__) def hoge(): logger.info('logging Start 2021') と、logging.info() を仕込んで、Cloud logger にログを出力してみると、logger.info() で出しているはずなのに、Cloud logger 上ではすべてエラーとして扱われてしまっています。
原因を特定するために、logger のログを見てみると logger.info() がすべて stderr標準エラーストリームへ出力されてしまっています。
{ &#34;textPayload&#34;: &#34;2021-02-20 21:26:51,012 - root:predict:36 - INFO: logging Start\n&#34;, ... }, &#34;timestamp&#34;: &#34;2021-02-20T12:26:51.013213826Z&#34;, &#34;severity&#34;: &#34;ERROR&#34;, &#34;labels&#34;: { ... }, &#34;logName&#34;: &#34;projects/.../logs/stderr&#34;, &#34;receiveTimestamp&#34;: &#34;2021-02-20T12:26:55."><meta name=keywords content="gcp,"><meta property="og:title" content="GKE 上にて Pythonで logger.info() を行うとCloud logging では stderr に保存され、すべてエラーになる問題への対処法"><meta property="og:description" content="Python のアプリケーションで、Cloud logger にログを出力したいときに
標準の Python logging モジュールを利用して、ログを出力する Python Cloud Logging package を使用する 上記の２つの方法があります。
不必要にパッケージを増やしたくはないので、1 の標準モジュールで Cloud Logger へ出力できないか試してみました。
標準の Python logging モジュールを試す 標準の logging モジュールでログを出力したいときに
import logging logger = logging.getLogger(__name__) def hoge(): logger.info('logging Start 2021') と、logging.info() を仕込んで、Cloud logger にログを出力してみると、logger.info() で出しているはずなのに、Cloud logger 上ではすべてエラーとして扱われてしまっています。
原因を特定するために、logger のログを見てみると logger.info() がすべて stderr標準エラーストリームへ出力されてしまっています。
{ &#34;textPayload&#34;: &#34;2021-02-20 21:26:51,012 - root:predict:36 - INFO: logging Start\n&#34;, ... }, &#34;timestamp&#34;: &#34;2021-02-20T12:26:51.013213826Z&#34;, &#34;severity&#34;: &#34;ERROR&#34;, &#34;labels&#34;: { ... }, &#34;logName&#34;: &#34;projects/.../logs/stderr&#34;, &#34;receiveTimestamp&#34;: &#34;2021-02-20T12:26:55."><meta property="og:type" content="article"><meta property="og:url" content="https://shunyaueta.com/posts/2021-03-03/"><meta property="og:image" content="https://shunyaueta.com/ogp.jpg"><meta property="article:section" content="posts"><meta property="article:published_time" content="2021-03-03T00:29:03+09:00"><meta property="article:modified_time" content="2021-03-03T00:29:03+09:00"><meta property="og:site_name" content="Shunya Ueta"><meta name=twitter:card content="summary_large_image"><meta name=twitter:image content="https://shunyaueta.com/ogp.jpg"><meta name=twitter:title content="GKE 上にて Pythonで logger.info() を行うとCloud logging では stderr に保存され、すべてエラーになる問題への対処法"><meta name=twitter:description content="Python のアプリケーションで、Cloud logger にログを出力したいときに
標準の Python logging モジュールを利用して、ログを出力する Python Cloud Logging package を使用する 上記の２つの方法があります。
不必要にパッケージを増やしたくはないので、1 の標準モジュールで Cloud Logger へ出力できないか試してみました。
標準の Python logging モジュールを試す 標準の logging モジュールでログを出力したいときに
import logging logger = logging.getLogger(__name__) def hoge(): logger.info('logging Start 2021') と、logging.info() を仕込んで、Cloud logger にログを出力してみると、logger.info() で出しているはずなのに、Cloud logger 上ではすべてエラーとして扱われてしまっています。
原因を特定するために、logger のログを見てみると logger.info() がすべて stderr標準エラーストリームへ出力されてしまっています。
{ &#34;textPayload&#34;: &#34;2021-02-20 21:26:51,012 - root:predict:36 - INFO: logging Start\n&#34;, ... }, &#34;timestamp&#34;: &#34;2021-02-20T12:26:51.013213826Z&#34;, &#34;severity&#34;: &#34;ERROR&#34;, &#34;labels&#34;: { ... }, &#34;logName&#34;: &#34;projects/.../logs/stderr&#34;, &#34;receiveTimestamp&#34;: &#34;2021-02-20T12:26:55."><meta itemprop=name content="GKE 上にて Pythonで logger.info() を行うとCloud logging では stderr に保存され、すべてエラーになる問題への対処法"><meta itemprop=description content="Python のアプリケーションで、Cloud logger にログを出力したいときに
標準の Python logging モジュールを利用して、ログを出力する Python Cloud Logging package を使用する 上記の２つの方法があります。
不必要にパッケージを増やしたくはないので、1 の標準モジュールで Cloud Logger へ出力できないか試してみました。
標準の Python logging モジュールを試す 標準の logging モジュールでログを出力したいときに
import logging logger = logging.getLogger(__name__) def hoge(): logger.info('logging Start 2021') と、logging.info() を仕込んで、Cloud logger にログを出力してみると、logger.info() で出しているはずなのに、Cloud logger 上ではすべてエラーとして扱われてしまっています。
原因を特定するために、logger のログを見てみると logger.info() がすべて stderr標準エラーストリームへ出力されてしまっています。
{ &#34;textPayload&#34;: &#34;2021-02-20 21:26:51,012 - root:predict:36 - INFO: logging Start\n&#34;, ... }, &#34;timestamp&#34;: &#34;2021-02-20T12:26:51.013213826Z&#34;, &#34;severity&#34;: &#34;ERROR&#34;, &#34;labels&#34;: { ... }, &#34;logName&#34;: &#34;projects/.../logs/stderr&#34;, &#34;receiveTimestamp&#34;: &#34;2021-02-20T12:26:55."><meta itemprop=datePublished content="2021-03-03T00:29:03+09:00"><meta itemprop=dateModified content="2021-03-03T00:29:03+09:00"><meta itemprop=wordCount content="228"><meta itemprop=image content="https://shunyaueta.com/ogp.jpg"><meta itemprop=keywords content="gcp,"><meta name=referrer content="no-referrer-when-downgrade"><style>body{font-family:Verdana,sans-serif;margin:auto;padding:20px;max-width:720px;text-align:left;background-color:#fff;word-wrap:break-word;overflow-wrap:break-word;line-height:1.5;color:#444}h1,h2,h3,h4,h5,h6,strong,b{color:#222}a{color:#3273dc}.title{text-decoration:none;border:0}.title span{font-weight:400}nav a{margin-right:10px}textarea{width:100%;font-size:16px}input{font-size:16px}content{line-height:1.6}table{width:100%}img{max-width:100%}code{padding:2px 5px;background-color:#f2f2f2}pre code{color:#222;display:block;padding:20px;white-space:pre-wrap;font-size:14px;overflow-x:auto}div.highlight pre{background-color:initial;color:initial}div.highlight code{background-color:unset;color:unset}blockquote{border-left:1px solid #999;color:#222;padding-left:20px;font-style:italic}footer{padding:25px;text-align:center}.helptext{color:#777;font-size:small}.errorlist{color:#eba613;font-size:small}ul.blog-posts{list-style-type:none;padding:unset}ul.blog-posts li{display:flex}ul.blog-posts li span{flex:0 0 130px}ul.blog-posts li a:visited{color:#8b6fcb}@media(prefers-color-scheme:dark){body{background-color:#333;color:#ddd}h1,h2,h3,h4,h5,h6,strong,b{color:#eee}a{color:#8cc2dd}code{background-color:#777}pre code{color:#ddd}blockquote{color:#ccc}textarea,input{background-color:#252525;color:#ddd}.helptext{color:#aaa}}</style><script async src="https://www.googletagmanager.com/gtag/js?id=G-JMJRQJT0Q3"></script>
<script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag("js",new Date),gtag("config","G-JMJRQJT0Q3")</script></head><body><header><a href=/ class=title><h2>hurutoriya</h2></a><nav><a href=/index.xml>RSS</a>
<a href=/about/>著者について</a></nav></header><main><h1>GKE 上にて Pythonで logger.info() を行うとCloud logging では stderr に保存され、すべてエラーになる問題への対処法</h1><p><i><time datetime=2021-03-03 pubdate>2021-03-03</time></i></p><content><p>Python のアプリケーションで、Cloud logger にログを出力したいときに</p><ol><li>標準の Python logging モジュールを利用して、ログを出力する</li><li>Python Cloud Logging package を使用する</li></ol><p>上記の２つの方法があります。</p><p>不必要にパッケージを増やしたくはないので、1 の標準モジュールで Cloud Logger へ出力できないか試してみました。</p><h2 id=標準の-python-logging-モジュールを試す>標準の Python logging モジュールを試す</h2><p>標準の logging モジュールでログを出力したいときに</p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-python data-lang=python><span style=display:flex><span><span style=color:#f92672>import</span> logging
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span>logger <span style=color:#f92672>=</span> logging<span style=color:#f92672>.</span>getLogger(__name__)
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span><span style=color:#66d9ef>def</span> <span style=color:#a6e22e>hoge</span>():
</span></span><span style=display:flex><span>	logger<span style=color:#f92672>.</span>info(<span style=color:#e6db74>&#39;logging Start 2021&#39;</span>)
</span></span></code></pre></div><p>と、logging.info() を仕込んで、Cloud logger にログを出力してみると、logger.info() で出しているはずなのに、Cloud logger 上ではすべてエラーとして扱われてしまっています。</p><p>原因を特定するために、logger のログを見てみると logger.info() がすべて <code>stderr</code>標準エラーストリームへ出力されてしまっています。</p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-bash data-lang=bash><span style=display:flex><span><span style=color:#f92672>{</span>
</span></span><span style=display:flex><span>  <span style=color:#e6db74>&#34;textPayload&#34;</span>: <span style=color:#e6db74>&#34;2021-02-20 21:26:51,012 - root:predict:36 - INFO:  logging Start\n&#34;</span>,
</span></span><span style=display:flex><span>	...
</span></span><span style=display:flex><span>  <span style=color:#f92672>}</span>,
</span></span><span style=display:flex><span>  <span style=color:#e6db74>&#34;timestamp&#34;</span>: <span style=color:#e6db74>&#34;2021-02-20T12:26:51.013213826Z&#34;</span>,
</span></span><span style=display:flex><span>  <span style=color:#e6db74>&#34;severity&#34;</span>: <span style=color:#e6db74>&#34;ERROR&#34;</span>,
</span></span><span style=display:flex><span>  <span style=color:#e6db74>&#34;labels&#34;</span>: <span style=color:#f92672>{</span>
</span></span><span style=display:flex><span>	...
</span></span><span style=display:flex><span>  <span style=color:#f92672>}</span>,
</span></span><span style=display:flex><span>  <span style=color:#e6db74>&#34;logName&#34;</span>: <span style=color:#e6db74>&#34;projects/.../logs/stderr&#34;</span>,
</span></span><span style=display:flex><span>  <span style=color:#e6db74>&#34;receiveTimestamp&#34;</span>: <span style=color:#e6db74>&#34;2021-02-20T12:26:55.050911180Z&#34;</span>
</span></span><span style=display:flex><span><span style=color:#f92672>}</span>
</span></span></code></pre></div><p>そのため、明示的に標準出力へ出力先を変更してみました。</p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-python data-lang=python><span style=display:flex><span><span style=color:#f92672>import</span> logging
</span></span><span style=display:flex><span><span style=color:#f92672>import</span> sys
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span>logger <span style=color:#f92672>=</span> logging<span style=color:#f92672>.</span>getLogger(__name__)
</span></span><span style=display:flex><span>handler <span style=color:#f92672>=</span> logging<span style=color:#f92672>.</span>StreamHandler(sys<span style=color:#f92672>.</span>stdout)
</span></span><span style=display:flex><span>logger<span style=color:#f92672>.</span>addHandler(handler)
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span><span style=color:#66d9ef>def</span> <span style=color:#a6e22e>hoge</span>():
</span></span><span style=display:flex><span>	logger<span style=color:#f92672>.</span>info(<span style=color:#e6db74>&#39;logging Start 2021&#39;</span>)
</span></span></code></pre></div><p>これで解決できているはずと、Cloud Logger を見てみると</p><p><img src=/posts/2021-03-03/images/clooudlogging_stderr.png alt="Cloud logging duplicate log in stderr and stdout"></p><p>なぜか、<code>stderr</code> への出力は残ったまま、<code>stdout</code>への出力が新たに増えました。このままでも INFO レベルでログは残せているので目的は達成できていますが、<code>stderr</code>への出力が残ってしまっているせいで Cloud logger 上でエラーが発生しているようになり問題です。なので、これを避けるために２つ目の方法である Python Cloud Logging package を利用してみます。 (というかパッケージをむやみに増やしたくないのだが利用せざるを得ない。)</p><h2 id=python-cloud-logging-package-を使用する>Python Cloud Logging package を使用する</h2><p>まず<a href=https://github.com/googleapis/python-logging>Python Client for Cloud Logging</a> のチュートリアルをすすめて行きます。</p><p>Cloud logging の Python package の<a href=https://github.com/googleapis/python-logging#quick-start>Quick Start</a> にてわかりやすく導入方法が紹介されています。ここで混乱しやすいのが、GCP の<a href=https://cloud.google.com/logging/docs/reference/libraries#cloud-console>Logging Client Libraries</a> のドキュメントではまず Service Account を作って、<code>GOOGLE_APPLICATION_CREDENTIALS</code> を使用して Cloud Logging の認証を行ってくださいと書かれています。</p><p>ですが、</p><ul><li><a href=https://googleapis.dev/python/google-api-core/latest/auth.html>GCP 上での VM でパッケージを使用するなら認証は必要ない</a> 。ただし、デフォルトの SA を使いたくない場合や、GCP 外などで動かしたい場合は SA が必要</li></ul><p>と本元のパッケージのドキュメントでは書かれており、こちらのほうが誤解が少なくていいですね。(公式ドキュメントだと、SA 作成時に <code>Project > Owner</code> を指定しろと書かれているんだけど、これって権限過多なのでは無いのだろうか??)</p><p>ちなみに GCP 上の認証過程はこちらのドキュメントが詳しく書かれているので、気になった方は御覧ください。</p><p><a href=https://cloud.google.com/docs/authentication/production>Authenticating as a service account</a></p><p>上記の認証仮定をまとめると</p><ol><li>GOOGLE_APPLICATION_CREDENTIALS を参照する</li><li>ADC (Application Default Credentials) が、コードに紐付けられている SA を使用する</li><li>ADC は各サービスの SA を利用する</li><li>1-3 が使用できなかった場合、認証エラーが発生する</li></ol><p>最終的に GKE 上で Cloud logging へログを出力するためには、
以下のコードで無事に <code>INFO</code> のログが<code>stderr</code> に吐き出されることなく、<code>stdout</code> のみに<code>INFO</code>として出力されるようになります。</p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-python data-lang=python><span style=display:flex><span><span style=color:#f92672>import</span> logging
</span></span><span style=display:flex><span><span style=color:#f92672>import</span> sys
</span></span><span style=display:flex><span><span style=color:#75715e># NOTE: GKE ではCotainerEngineHandler が必要</span>
</span></span><span style=display:flex><span><span style=color:#f92672>from</span> google.cloud.logging.handlers <span style=color:#f92672>import</span> ContainerEngineHandler
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span>logger <span style=color:#f92672>=</span> logging<span style=color:#f92672>.</span>getLogger(__name__)
</span></span><span style=display:flex><span><span style=color:#75715e># NOTE: stream で stdout を指定する</span>
</span></span><span style=display:flex><span>logger<span style=color:#f92672>.</span>addHandler(ContainerEngineHandler(name<span style=color:#f92672>=</span>__name__, stream<span style=color:#f92672>=</span>sys<span style=color:#f92672>.</span>stdout))
</span></span><span style=display:flex><span><span style=color:#75715e># NOTE: ログが重複して出力されるので、propagate を切る</span>
</span></span><span style=display:flex><span>logger<span style=color:#f92672>.</span>propagate <span style=color:#f92672>=</span> <span style=color:#66d9ef>False</span>
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span>logger<span style=color:#f92672>.</span>info(<span style=color:#e6db74>&#39;Hello Cloud Logging.&#39;</span>)
</span></span></code></pre></div><h2 id=appendix>Appendix</h2><ul><li><a href=https://docs.python.org/3/howto/logging.html>https://docs.python.org/3/howto/logging.html</a></li><li><a href=https://cloud.google.com/logging/docs/setup/python>https://cloud.google.com/logging/docs/setup/python</a></li><li><a href=https://www.ai-shift.co.jp/techblog/1217>https://www.ai-shift.co.jp/techblog/1217</a></li><li><a href=https://stackoverflow.com/questions/48078051/duplicate-log-entries-with-google-cloud-stackdriver-logging-of-python-code-on-ku>https://stackoverflow.com/questions/48078051/duplicate-log-entries-with-google-cloud-stackdriver-logging-of-python-code-on-ku</a><ul><li>同じような質問があった</li></ul></li></ul><h2>関連しているかもしれない記事</h2><ul><li><a href=/posts/2019-10-03/>遅すぎる `pandas.read_gbq` を使わずに、Google BigQueryから高速にデータを読み込む</a></li><li><a href=/posts/2019-09-24/>How to connect the Google Compute Engine via Visual Studio Code</a></li></ul><h2>Support</h2>記事をお読みくださりありがとうございます。
このウェブサイトの運営を支援していただける方を募集しています。
もしよろしければ、<a href=https://www.buymeacoffee.com/hurutoriya>Buy Me a Coffee</a> からサポート(投げ銭)していただけると、記事の執筆、情報発信のモチベーションに繋がります✨<p>--</p>記事を楽しめましたか？
<a href=/index.xml>RSS</a>で更新情報を配信しているので、お好きなフィードリーダーで購読してみてください。</br>記事への感想などの<a href=https://forms.gle/g4rNMwPL799uHXQg7>おたより</a>をおまちしてます。
(おたより機能はGoogle フォームで実現しており、hurutoriya 個人が管理するGoogleフォームに記録されます。)
お気軽にお送りください。
お返事はメールアドレス入力があればメールでさせていただきます。
もちろんお返事を希望せずに単なる感想だけでも大歓迎です。</content><p><a href=https://shunyaueta.com/tags/gcp/>#gcp</a></p><script src=https://giscus.app/client.js data-repo=hurutoriya/hurutoriya.github.io data-repo-id="MDEwOlJlcG9zaXRvcnk2MDgyNTY1Nw==" data-category=Comments data-category-id=DIC_kwDOA6AgOc4CAQTX data-mapping=pathname data-reactions-enabled=1 data-emit-metadata=0 data-theme=dark data-lang=ja crossorigin=anonymous async></script></main><footer>Made with <a href=https://github.com/janraasch/hugo-bearblog/>Hugo ʕ•ᴥ•ʔ Bear</a></footer></body></html>